### ISSUE TITLE
Unable decode newest marian model via amun program

### ISSUE THREAD

**Issue by lkfo415579** [marian-nmt/amun#6]
XD, can't use the newest amun program to decode marian model (amun type). It said there is a unknown node or something, please take a look.

Is amun still faster or marian-decoder faster now?

```
GPU : 1080TI
OS : ubuntu 16.0.4

Amun repo's commit : 65d379b183265435f6945ae3ad8cb4cba28674bb (Date:   Fri Oct 5 09:40:53 2018 +0100)
Marian repo's commit (v1.6.0): b2a945c750a9daa2210fdd2198345cadd8628d24 (Date:   Sun Sep 16 12:05:32 2018 +0200)

Error Messages : 
[Fri Oct 12 14:08:56 2018] (I) Options: allow-unk: false
beam-size: 12
cpu-threads: 0
devices: [0, 1, 2]
gpu-threads: 1
log-info: info
log-progress: info
max-length: 500
max-length-multiple: 3
maxi-batch: 100
mini-batch: 10
mini-batch-words: 0
n-best: false
no-debpe: false
normalize: true
relative-paths: false
return-alignment: false
return-nematus-alignment: false
return-soft-alignment: false
scorers:
  F0:
    path: News_model-en-zh/model_revo_amun.npz.dev.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab: News_model-en-zh/vocab.en.yml
target-vocab: News_model-en-zh/vocab.zh.yml
tensor-cores: false
use-fused-softmax: true
weights:
  F0: 1
wipo: false

[Fri Oct 12 14:08:58 2018] (I) Loading scorers...
Error: Tensor not found:decoder_c_tt
Aborted (core dumped)

```

**Comment by snukky** [comment]
It's a known bug (https://github.com/marian-nmt/marian-dev/issues/333) that will be fixed soon in marian-dev. You may fix your trained models with the script mentioned in that thread.

**Comment by snukky** [comment]
Fixed in marian-nmt/marian-dev

**Comment by CatarinaSilva** [comment]
@snukky, not sure if it's of interest to you guys, but I found the same problem and the fix does not work for a particular case:

* You have a base model trained with a previous version of Marian (so this one has the `decoder_c_tt` field)
* You use this previous model as a pretrained model (which does not generate any error) and train using Marian 1.6.0 
* You have the previous version of Amun, with which you try to decode

The fix of injecting `decoder_c_tt` does not work in this case, because the model has the field from the pretrained one. I looked in to the several fields and noticed different shapes, in particular (the first shape if the one of the previous model and the last the one of the recent model):

```
ff_state_b
(1024,)
(1, 1024)
----------------------------------------
encoder_r_bx
(1024,)
(1, 1024)
----------------------------------------
ff_logit_ctx_b
(512,)
(1, 512)
----------------------------------------
decoder_b
(2048,)
(1, 2048)
----------------------------------------
ff_logit_prev_b
(512,)
(1, 512)
----------------------------------------
ff_logit_lstm_b
(512,)
(1, 512)
----------------------------------------
decoder_b_att
(2048,)
(1, 2048)
----------------------------------------
decoder_bx_nl
(1024,)
(1, 1024)
----------------------------------------
ff_logit_b
(60400,)
(1, 60400)
----------------------------------------
encoder_b
(2048,)
(1, 2048)
----------------------------------------
decoder_bx
(1024,)
(1, 1024)
----------------------------------------
encoder_bx
(1024,)
(1, 1024)
----------------------------------------
decoder_c_tt
(1,)
(1, 1)
----------------------------------------
encoder_r_b
(2048,)
(1, 2048)
----------------------------------------
special:model.yml
(274,)
(785,)
----------------------------------------
decoder_b_nl
(2048,)
(1, 2048)
----------------------------------------
```

What worked for me was to flatten these shapes. Although I think here it was my fault by not bumping both versions at the same time, I think this information might be useful whether someone makes my mistake or if they want to run older models in the new Amun, I guess, so I'll leave it here in the issue.

Also, I don't know what happens with the pretraining and the newer Amun version, but it might be good to try that and make sure your fixes work in that case :)

**Comment by snukky** [comment]
Thanks for the comment! So, the older Amun expects flattened shapes and the new Amun may expect unflattened ones? I didn't notice any important updates in Amun for months.

**Comment by CatarinaSilva** [comment]
@snukky  

I tried to go through the last commits but didn't find a direct explanation also, might need a bit more digging. 

This was really just by looking at the models and having the information that running `amun` for the old model worked and for the new one produced the error `"Some other kind of error during some_function"`. 

I then noticed that my amun version was compiled on the 13th of September, which looking into some commits seems to be before there was a bump of Marian version and other small changes.
